### ISSUE TITLE
Add LICENSE or COPYING file

### ISSUE THREAD

**Issue by CorruptedArk** [SarahHeinzHouseFRC/frcsim2020#15]
Hi team 3260, I'm a mentor for team 1528, Monroe Trojan Robotics. This project looks very useful and I believe it has a lot of potential. I think it would be helpful if this project explicitly laid out the rights of users and developers interested in it. If you are happy with it being free as in speech, I would recommend either following WPILib's example with a permissive license like the BSD license or use a copyleft license like the GPL. This would explicitly allow distribution of modified forks of your project.

**Comment by ptkinvent** [comment]
Hello CorruptedArk, this is a great suggestion. I will add a GPL shortly -- let me know if you have any additional thoughts.

**Comment by ptkinvent** [comment]
Resolved in  20e0e15.
